### PR TITLE
Updated versions of pax exam and pax runner

### PR DESCRIPTION
**Pull request by remast**
I did some minor updates:
 Updated pax exam version from 2.1 to 2.2. 
 Updated pax runner version from 1.7.3 to 1.7.6

Info:
 I did not update pax exam to 2.3 because the tests did not run successfully with version 2.3. I don't have enough experience to fix that so I just left it.

### CODE REVIEW

**Comment by tonit** [comment]
Thanks, Jan. Any reason why you just pulled Exam to 2.2 and not 2.4.0-RC1 (which is the latest released version). Don't get me wrong, 2.2 is better than 2.1 just curious. ;)

**Comment by tonit** [comment]
Yes, there are some changes required, but those are minor. I had the Learn stuff running on 2.3.0 for most parts a while ago locally, but never finished & pushed that part. Should not be hard to do.

**Comment by remast** [comment]
Actually I was just experimenting with pax exam and I was wondering why such an "old" version is used. Then I tried to upgrade the version and I stopped when I had to dig deeper. Of course it would be better to update to 2.3 but making an update to 2.2 is a first step in the right direction.

**Comment by tonit** [comment]
Thanks!

**Pull request merged**
